version: '3.4'

services:
  proxy:
    image: traefik:v2.9
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      # Add a constraint to only use services with the label for this stack
      # from the env var TRAEFIK_TAG
      - --providers.docker.constraints=Label(`traefik.constraint-label-stack`, `${TRAEFIK_TAG?Variable not set}`)
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      - --entrypoints.web.address=:80
      - --entrypoints.web.forwardedHeaders.insecure=true
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '${PORT-80}:80'
  frontend:
    build:
      context: frontend
    depends_on:
      - api
    restart: on-failure
    environment:
      - TZ=Etc/UTC
    env_file:
      - env-frontend.env
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=${TRAEFIK_TAG?Variable not set}
      - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-http.rule=PathPrefix(`/`)
      - traefik.http.services.${STACK_NAME?Variable not set}-frontend.loadbalancer.server.port=3000
